import React, { useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, RefreshControl, Text, View, useWindowDimensions } from 'react-native';
import { ArrowLeft, UserRound } from 'lucide-react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Button, colors, ErrorMessage, fonts, ui } from '../components/ui';
import { useRepository } from '../data/RepositoryProvider';
import { subscribeSocialInvalidation } from './events';
import { FollowButton } from './FollowButton';
import { SharedEntryCard } from './SharedEntryCard';
import { SharedEntryDetail } from './SharedEntryDetail';
import type { CollectorProfile, SharedEntry } from './types';
import { VisibleCollectionScreen } from './VisibleCollectionScreen';

export function CollectorProfileScreen({ publisherId, onClose }: { publisherId: string; onClose: () => void }) {
  const repository = useRepository(); const { width } = useWindowDimensions(); const columns = width >= 1000 ? 4 : width >= 650 ? 3 : 2;
  const [profile, setProfile] = useState<CollectorProfile | null>(null); const [entries, setEntries] = useState<SharedEntry[]>([]); const [cursor, setCursor] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [revision, setRevision] = useState(0); const [selected, setSelected] = useState<SharedEntry | null>(null); const [collectionId, setCollectionId] = useState<string | null>(null);
  useEffect(() => subscribeSocialInvalidation(() => setRevision(value => value + 1)), []);
  useEffect(() => { let active = true; setLoading(true); setError(''); void Promise.all([repository.getCollector(publisherId), repository.listCollectorEntries(publisherId)]).then(([nextProfile, page]) => { if (active) { setProfile(nextProfile); setEntries(page.items); setCursor(page.nextCursor); } }).catch(reason => { if (active) setError(reason instanceof Error ? reason.message : 'Collector unavailable.'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [publisherId, repository, revision]);
  async function loadMore() { if (!cursor) return; try { const page = await repository.listCollectorEntries(publisherId, cursor); setEntries(current => [...current, ...page.items.filter(item => !current.some(existing => existing.id === item.id))]); setCursor(page.nextCursor); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load more items.'); } }
  function updateEntry(next: SharedEntry) { setEntries(current => current.map(item => item.id === next.id ? next : item)); setSelected(current => current?.id === next.id ? next : current); }
  const handle = profile?.username ?? 'collector';
  return <SafeAreaView style={{ flex: 1, backgroundColor: colors.paper }}><View style={[ui.row, { padding: 16, borderBottomWidth: 1, borderColor: colors.line }]}><Button title="Back" icon={ArrowLeft} secondary onPress={onClose} /></View><FlatList key={columns} data={entries} keyExtractor={entry => entry.id} numColumns={columns} contentContainerStyle={{ padding: width >= 900 ? 32 : 16, flexGrow: 1, paddingBottom: 40 }} refreshControl={<RefreshControl refreshing={loading} onRefresh={() => setRevision(value => value + 1)} tintColor={colors.green} />} ListHeaderComponent={<View style={{ gap: 12, paddingBottom: 18 }}><View style={[ui.row, { gap: 12 }]}><View style={{ width: 52, height: 52, borderRadius: 26, backgroundColor: colors.pale, alignItems: 'center', justifyContent: 'center' }}><Text style={{ color: colors.green, fontFamily: fonts.bold, fontSize: 20 }}>{handle[0]?.toUpperCase() ?? 'C'}</Text></View><View><Text style={[ui.title, { fontSize: 30 }]}>@{handle}</Text><Text style={ui.muted}>Collector</Text></View></View>{profile ? <FollowButton collector={profile} onChanged={relationship => setProfile(current => current ? { ...current, relationship } : current)} /> : null}<ErrorMessage message={error} /></View>} renderItem={({ item }) => <View style={{ width: `${100 / columns}%`, padding: 7 }}><SharedEntryCard entry={item} accessRevision={revision} onOpen={() => setSelected(item)} onOpenCollector={() => undefined} onLikeChanged={updateEntry} /></View>} ListEmptyComponent={loading ? <ActivityIndicator color={colors.green} style={{ margin: 30 }} /> : !error ? <View style={{ alignItems: 'center', padding: 30, gap: 8 }}><UserRound size={38} color={colors.muted} /><Text style={ui.muted}>No shared items to show.</Text></View> : null} ListFooterComponent={cursor ? <Button title="Load more" secondary onPress={() => { void loadMore(); }} style={{ margin: 8 }} /> : null} />{selected ? <SharedEntryDetail entry={selected} collector={profile} accessRevision={revision} onClose={() => setSelected(null)} onOpenCollection={() => { setCollectionId(selected.collectionId); setSelected(null); }} onEntryChanged={updateEntry} /> : null}{collectionId ? <VisibleCollectionScreen collectionId={collectionId} onClose={() => setCollectionId(null)} /> : null}</SafeAreaView>;
}
