import React, { useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, RefreshControl, ScrollView, Text, TextInput, View, useWindowDimensions } from 'react-native';
import { Image } from 'expo-image';
import { SafeAreaView } from 'react-native-safe-area-context';
import { FolderHeart, Grid2X2, LogOut, Pencil, Pin as PinIcon, Plus, Search, ShieldCheck, Trash2, X } from 'lucide-react-native';
import type { Collection, Pin } from '../domain/models';
import { useRepository } from '../data/RepositoryProvider';
import { useLibrary } from '../data/useLibrary';
import { auth } from '../auth/session';
import { Brand, Button, colors, ErrorMessage, fonts, messageOf, PrivateBadge, Sheet, ui } from '../components/ui';
import { PinArtwork } from '../components/PinArtwork';
import { CollectionEditor, ConfirmDelete, PinEditor } from './Editors';
type Dialog = { type: 'collection'; collection?: Collection } | { type: 'pin'; pin?: Pin } | { type: 'detail'; pin: Pin } | { type: 'delete-pin'; pin: Pin } | { type: 'delete-collection'; collection: Collection } | { type: 'settings' } | { type: 'delete-account' } | null;
export function LibraryScreen({ email, onExitDemo }: { email: string; onExitDemo?: () => void }) {
  const repository = useRepository();
  const { width } = useWindowDimensions(); const wide = width >= 900; const columns = width >= 1250 ? 4 : width >= 650 ? 3 : 2;
  const [selected, setSelected] = useState<string>(); const [search, setSearch] = useState(''); const [query, setQuery] = useState(''); const [dialog, setDialog] = useState<Dialog>(null); const [accountError, setAccountError] = useState(''); const [signingOut, setSigningOut] = useState(false);
  useEffect(() => { const timeout = setTimeout(() => setQuery(search), 250); return () => clearTimeout(timeout); }, [search]);
  const library = useLibrary(selected, query); const collection = library.collections.find(item => item.id === selected);
  function changed() { setDialog(null); library.refresh(); }
  async function signOut() {
    setAccountError(''); setSigningOut(true);
    try {
      if (onExitDemo) { await repository.deleteAccount(); await Image.clearMemoryCache(); onExitDemo(); }
      else { try { await auth.signOut(); } finally { await Image.clearMemoryCache(); } }
    } catch (e) { setAccountError(messageOf(e)); setSigningOut(false); }
  }
  const collectionColors = ['#E6ECD9', '#F0DDD0', '#DDE8EC', '#EBE0EC', '#F1E9CD'];
  function collectionLink(item?: Collection, index = 0) {
    const active = selected === item?.id;
    return <Pressable key={item?.id ?? 'all'} accessibilityRole="button" accessibilityState={{ selected: active }} onPress={() => { setSelected(item?.id); setSearch(''); }} style={({ pressed }) => [{ flexDirection: 'row', alignItems: 'center', gap: 10, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 12, backgroundColor: active ? colors.pale : pressed ? '#F0F2EC' : 'transparent', marginBottom: wide ? 5 : 0, borderWidth: wide ? 0 : 1, borderColor: active ? '#C7D6C6' : colors.line, maxWidth: wide ? '100%' : 210 }]}>{item ? <View style={{ height: 25, width: 25, borderRadius: 8, backgroundColor: collectionColors[index % collectionColors.length], alignItems: 'center', justifyContent: 'center' }}><FolderHeart size={14} color={colors.green} /></View> : <Grid2X2 size={20} color={colors.green} />}<Text numberOfLines={1} style={{ color: active ? colors.green : colors.muted, fontFamily: active ? fonts.bold : fonts.medium, fontSize: 14, flexShrink: 1 }}>{item?.name ?? 'All pins'}</Text></Pressable>;
  }
  const header = <View style={{ paddingHorizontal: 8, paddingBottom: 24, gap: 24 }}>
    {onExitDemo ? <View style={{ backgroundColor: colors.sand, borderRadius: 12, padding: 14, gap: 12, flexDirection: 'row', alignItems: 'center' }}><Text style={[ui.text, { fontSize: 12, lineHeight: 18, flex: 1 }]}>Demo collection · Your changes reset when you leave.</Text><Button title="Exit demo" secondary onPress={() => { void signOut(); }} loading={signingOut} /><ErrorMessage message={accountError} /></View> : null}
    <View style={[ui.row, { justifyContent: 'space-between', marginTop: 12 }]}><Text style={{ fontFamily: fonts.bold, fontSize: 11, letterSpacing: 2, color: colors.coral }}>YOUR PRIVATE COLLECTION</Text><PrivateBadge /></View>
    <View style={{ gap: 12 }}><View style={[ui.row, { alignItems: 'flex-start', justifyContent: 'space-between' }]}><Text style={[ui.title, { flex: 1, fontSize: wide ? 52 : 40, lineHeight: wide ? 57 : 44 }]}>{collection?.name ?? 'Small pins.\nBig memories.'}</Text>{collection ? <Pressable accessibilityRole="button" accessibilityLabel="Edit this collection" onPress={() => setDialog({ type: 'collection', collection })} style={{ padding: 12, backgroundColor: colors.card, borderRadius: 12, borderWidth: 1, borderColor: colors.line }}><Pencil size={18} color={colors.green} /></Pressable> : null}</View><Text style={[ui.muted, { maxWidth: 520 }]}>{collection ? collection.description || 'A little corner for the things you love.' : 'Every souvenir, lucky find, and thoughtful gift. All in one place.'}</Text></View>
    <View style={[ui.row, { flexWrap: 'wrap', gap: 12 }]}><View style={[ui.row, { flex: 1, minWidth: 180, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, borderRadius: 12, paddingHorizontal: 14, minHeight: 48 }]}><Search size={18} color={colors.muted} /><TextInput accessibilityLabel="Search pins" placeholder="Find a pin by name…" placeholderTextColor="#8B968D" value={search} onChangeText={setSearch} style={{ flex: 1, fontFamily: fonts.body, fontSize: 14, color: colors.ink, paddingVertical: 12 }} />{search ? <Pressable accessibilityRole="button" accessibilityLabel="Clear search" onPress={() => setSearch('')} hitSlop={10}><X size={16} color={colors.muted} /></Pressable> : null}</View><Button title="Add a pin" icon={Plus} onPress={() => setDialog(library.collections.length ? { type: 'pin' } : { type: 'collection' })} disabled={library.loading && !library.collections.length} /></View>
    {!wide ? <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8 }}>{collectionLink()}{library.collections.map((item, index) => collectionLink(item, index))}<Pressable accessibilityRole="button" accessibilityLabel="New collection" onPress={() => setDialog({ type: 'collection' })} style={{ padding: 12, justifyContent: 'center' }}><Plus size={21} color={colors.green} /></Pressable></ScrollView> : null}
    <View style={[ui.row, { justifyContent: 'space-between', borderBottomWidth: 1, borderColor: colors.line, paddingBottom: 17 }]}><Text style={{ fontFamily: fonts.bold, fontSize: 15, color: colors.ink }}>{query ? 'Search results' : 'Your pins'} <Text style={{ color: colors.muted, fontFamily: fonts.body }}>{library.loading ? '' : `(${library.total})`}</Text></Text><Text style={[ui.muted, { fontSize: 12 }]}>Newest first</Text></View>
    <ErrorMessage message={library.error} />{library.error ? <Button title="Try again" secondary onPress={library.refresh} /> : null}
    {library.photoError ? <View style={{ padding: 14, backgroundColor: colors.sand, borderRadius: 12, gap: 10 }}><Text style={[ui.text, { fontSize: 13 }]}>{library.photoError}</Text><Button title="Retry photos" secondary onPress={() => { void library.refreshPhotos(); }} /></View> : null}
  </View>;
  return <SafeAreaView style={{ flex: 1, backgroundColor: colors.paper }}><View style={[ui.row, { paddingHorizontal: wide ? 32 : 24, paddingVertical: 18, justifyContent: 'space-between', borderBottomWidth: 1, borderColor: colors.line, backgroundColor: colors.card }]}><Brand small={!wide} /><View style={ui.row}>{wide ? <Text style={ui.muted}>A little more organized. A lot more you.</Text> : null}<Pressable accessibilityRole="button" accessibilityLabel="Account settings" onPress={() => setDialog({ type: 'settings' })} style={{ width: 38, height: 38, alignItems: 'center', justifyContent: 'center', borderRadius: 19, backgroundColor: colors.pale }}><Text style={{ color: colors.green, fontFamily: fonts.bold }}>{email[0]?.toUpperCase() ?? 'Y'}</Text></Pressable></View></View>
    <View style={{ flex: 1, flexDirection: 'row', width: '100%', maxWidth: 1500, alignSelf: 'center' }}>
      {wide ? <View style={{ width: 246, padding: 24, borderRightWidth: 1, borderColor: colors.line }}><Text style={{ fontFamily: fonts.bold, fontSize: 10, color: colors.muted, letterSpacing: 1.6, marginTop: 16, marginBottom: 20 }}>YOUR SHELVES</Text>{collectionLink()}<View style={[ui.row, { justifyContent: 'space-between', marginTop: 26, marginBottom: 14 }]}><Text style={{ fontFamily: fonts.bold, fontSize: 11, color: colors.muted, letterSpacing: 1 }}>COLLECTIONS</Text><Pressable accessibilityRole="button" accessibilityLabel="New collection" hitSlop={12} onPress={() => setDialog({ type: 'collection' })}><Plus size={18} color={colors.green} /></Pressable></View><ScrollView>{library.collections.map((item, index) => collectionLink(item, index))}{!library.collections.length && !library.loading ? <Text style={[ui.muted, { fontSize: 13, paddingHorizontal: 12 }]}>Your next little obsession starts here.</Text> : null}</ScrollView><View style={{ backgroundColor: colors.pale, borderRadius: 16, padding: 17, gap: 10, marginTop: 20 }}><ShieldCheck size={23} color={colors.green} strokeWidth={1.5} /><Text style={{ fontFamily: fonts.medium, color: colors.green, fontSize: 13 }}>A collection just for you.</Text><Text style={[ui.muted, { fontSize: 12, lineHeight: 18 }]}>Your pins, photos, and stories stay private.</Text></View></View> : null}
      <FlatList key={columns} data={library.pins} keyExtractor={item => item.id} numColumns={columns} style={{ flex: 1 }} contentContainerStyle={{ padding: wide ? 32 : 16, paddingBottom: 50, flexGrow: 1 }} ListHeaderComponent={header} refreshControl={<RefreshControl refreshing={library.loading} onRefresh={library.refresh} tintColor={colors.green} />} renderItem={({ item }) => {
        const image = library.images[item.id]; const itemCollection = library.collections.find(c => c.id === item.collection_id);
        return <View style={{ width: `${100 / columns}%`, padding: 8 }}><Pressable accessibilityRole="button" accessibilityLabel={`Open ${item.title}`} onPress={() => setDialog({ type: 'detail', pin: item })} style={({ pressed }) => [{ borderWidth: 1, borderColor: colors.line, borderRadius: 17, backgroundColor: colors.card, overflow: 'hidden', opacity: pressed ? 0.85 : 1 }]}><View style={{ aspectRatio: 1, backgroundColor: '#ECEFE7', alignItems: 'center', justifyContent: 'center' }}>{image ? <Image source={{ uri: image.thumbnailUrl }} cachePolicy="memory" style={{ width: '100%', height: '100%' }} contentFit="cover" transition={180} accessibilityLabel={item.title} /> : <View style={{ alignItems: 'center', gap: 8 }}><PinIcon size={36} color="#94A18F" strokeWidth={1.2} /><Text style={{ fontSize: 11, color: colors.muted, fontFamily: fonts.body }}>No photo loaded</Text></View>}</View><View style={{ padding: 14, gap: 6 }}><Text numberOfLines={1} style={{ fontFamily: fonts.bold, fontSize: 14, color: colors.ink }}>{item.title}</Text><Text numberOfLines={1} style={[ui.muted, { fontSize: 11, lineHeight: 16 }]}>{itemCollection?.name ?? 'Your collection'}</Text></View></Pressable></View>;
      }} ListEmptyComponent={library.loading ? <View style={{ alignItems: 'center', padding: 50 }}><ActivityIndicator color={colors.green} /><Text style={[ui.muted, { marginTop: 12 }]}>Finding your favorites…</Text></View> : !library.error ? <View style={{ alignItems: 'center', paddingVertical: 15, paddingHorizontal: 20, gap: 18 }}><PinArtwork compact /><Text style={[ui.title, { fontSize: 31, textAlign: 'center' }]}>{query ? 'No pins found.' : 'Your next favorite belongs here.'}</Text><Text style={[ui.muted, { textAlign: 'center', maxWidth: 340 }]}>{query ? 'Try another name, or clear your search to see all your pins.' : library.collections.length ? 'Add your first pin and start keeping the stories behind your collection.' : 'Create a collection, then add a photo of your first pin. It’s that simple.'}</Text><Button title={query ? 'Clear search' : library.collections.length ? 'Add your first pin' : 'Create your first collection'} icon={query ? undefined : Plus} onPress={() => query ? setSearch('') : setDialog(library.collections.length ? { type: 'pin' } : { type: 'collection' })} /></View> : null} ListFooterComponent={library.hasMore ? <Button title="Load more pins" secondary onPress={() => { void library.loadMore(); }} loading={library.moreLoading} style={{ margin: 16 }} /> : library.pins.length ? <Text style={[ui.muted, { textAlign: 'center', fontSize: 12, marginTop: 28 }]}>All caught up. Time to find your next favorite.</Text> : null} />
    </View>
    {dialog?.type === 'collection' ? <CollectionEditor collection={dialog.collection} onClose={() => setDialog(null)} onSaved={value => { setSelected(value.id); changed(); }} onDelete={() => { if (dialog.collection) setDialog({ type: 'delete-collection', collection: dialog.collection }); }} /> : null}
    {dialog?.type === 'pin' ? <PinEditor pin={dialog.pin} image={dialog.pin ? library.images[dialog.pin.id] : undefined} collections={library.collections} initialCollection={selected} onClose={() => setDialog(null)} onSaved={changed} /> : null}
    {dialog?.type === 'detail' ? <Sheet title={dialog.pin.title} onClose={() => setDialog(null)}><View style={{ aspectRatio: 1, backgroundColor: colors.pale, borderRadius: 18, overflow: 'hidden', alignItems: 'center', justifyContent: 'center' }}>{library.images[dialog.pin.id] ? <Image source={{ uri: library.images[dialog.pin.id]!.url }} cachePolicy="memory" style={{ width: '100%', height: '100%' }} contentFit="contain" accessibilityLabel={dialog.pin.title} /> : <PinIcon size={60} color="#94A18F" />}</View><View style={[ui.row, { justifyContent: 'space-between' }]}><Text style={[ui.muted, { flex: 1 }]}>{library.collections.find(c => c.id === dialog.pin.collection_id)?.name}</Text><PrivateBadge /></View>{dialog.pin.notes ? <Text style={ui.text}>{dialog.pin.notes}</Text> : <Text style={ui.muted}>A little treasure, waiting for its story.</Text>}<Text style={[ui.muted, { fontSize: 12 }]}>Added {new Date(dialog.pin.created_at).toLocaleDateString(undefined, { month: 'long', day: 'numeric', year: 'numeric' })}</Text><View style={ui.row}><Button title="Edit pin" secondary icon={Pencil} onPress={() => setDialog({ type: 'pin', pin: dialog.pin })} style={{ flex: 1 }} /><Button title="Delete" secondary danger icon={Trash2} onPress={() => setDialog({ type: 'delete-pin', pin: dialog.pin })} /></View></Sheet> : null}
    {dialog?.type === 'delete-pin' ? <ConfirmDelete kind="pin" name={dialog.pin.title} action={() => repository.deletePin(dialog.pin.id)} onClose={() => setDialog(null)} onDeleted={changed} /> : null}
    {dialog?.type === 'delete-collection' ? <ConfirmDelete kind="collection" name={dialog.collection.name} action={() => repository.deleteCollection(dialog.collection.id)} onClose={() => setDialog(null)} onDeleted={() => { setSelected(undefined); changed(); }} /> : null}
    {dialog?.type === 'settings' ? <Sheet title="Your little corner" onClose={() => setDialog(null)} busy={signingOut}><View style={{ gap: 8 }}><Text style={ui.label}>{onExitDemo ? "EXPLORING AS" : "SIGNED IN AS"}</Text><Text style={ui.text}>{email}</Text></View><View style={{ backgroundColor: colors.pale, padding: 18, borderRadius: 14, gap: 10 }}><PrivateBadge /><Text style={ui.text}>{onExitDemo ? "This is a temporary demo. Photos are not uploaded. Your collection changes reset when you leave or reload." : "Your collections are visible only to your account. Your photos are stored privately."}</Text><Text style={ui.muted}>This early version supports up to 50 collections and 500 pins per account.</Text></View><ErrorMessage message={accountError} /><Button title={onExitDemo ? "Exit demo" : "Sign out"} secondary icon={LogOut} loading={signingOut} onPress={() => { void signOut(); }} />{!onExitDemo ? <Button title="Delete my account" secondary danger icon={Trash2} disabled={signingOut} onPress={() => setDialog({ type: 'delete-account' })} /> : null}</Sheet> : null}
    {dialog?.type === 'delete-account' ? <ConfirmDelete kind="account" name="your account" action={() => repository.deleteAccount()} onClose={() => setDialog(null)} onDeleted={() => { setDialog({ type: 'settings' }); void signOut(); }} /> : null}
  </SafeAreaView>;
}
